### PR TITLE
show link to revoke.cash if unlock fails at assert

### LINKED ISSUE #192: Unlock does not work if TRAC token was not transferred for entire amount
For tokens contracts which checks that there is no approval for a specific operator as part of execution of the `approve()` call, the OB UI unlock operation could fail if the user previously did not use entire amount of unlocked tokens (e.g. with the "Infinite Unlock" feature enabled).

image

Here is the TRAC token: https://etherscan.io/address/0xaa7a9ca87d3694b5755f213b5d04094b8d0f0a6f#code.

```solidity
   function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
    require(_to != address(0));
    require(_value <= balances[_from]);
    require(_value <= allowed[_from][msg.sender]);

    balances[_from] = balances[_from].sub(_value);
    balances[_to] = balances[_to].add(_value);
    allowed[_from][msg.sender] = allowed[_from][msg.sender].sub(_value); // <-- amount of approved tokens is decreased 
    Transfer(_from, _to, _value);
    return true;
   }

   function approve(address _spender, uint256 _value) public returns (bool) {
    // mitigating the race condition
    assert(allowed[msg.sender][_spender] == 0 || _value == 0); // <-- if there is still an approval even for 1 wei of tokens it will revert
    
    allowed[msg.sender][_spender] = _value;
    Approval(msg.sender, _spender, _value);
    return true;
   }
```

Consider to identify a possible issue with the approval on the stage of the `eth_gasEstimate` call and output a message something like "There is problem with the token unlock. Try to revoke previous approval if any on https://revoke.cash/ and unlock the tokens again."

### PR DESCRIPTION
**Pull request by dan13ram**
Closes #192

### CODE REVIEW

File: packages/react-app/src/components/bridge/UnlockButton.jsx [hunk 1]
```diff
@@ -41,7 +41,24 @@ export const UnlockButton = () => {
     if (!unlockLoading && !allowed && valid()) {
       approve().catch(error => {
         if (error && error.message) {
-          showError(error.message);
+          if (error.data === 'Bad instruction fe') {
```
Comment (akolotov) [inline packages/react-app/src/components/bridge/UnlockButton.jsx:44]: It is not correct to rely only on such message. Because it is specific to usage of the `assert` function in the Solidity code. Another token could use `revert` instead of `assert` to identify the same case but the error will be different.

**Review by akolotov — COMMENTED** [review]
Please make the solution more common.
